services:
  smtp:
    image: ixdotai/smtp:v0.7.6@sha256:2de999bee1fecf58ff5783fd51b92ef74ed3e0ca6c493bd5547b7ceff5ca6099
    container_name: smtp
    ports:
      - 127.0.0.1:25:25
    env_file:
      - ./environments/smtp.env
  postgres:
    image: postgres:17@sha256:bac8128cd62a35471a1e97966861aa2ac88c8d2f408767a425ae70695a607c99
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: my_data_db
      POSTGRES_USER: my_data_user
      POSTGRES_PASSWORD: my_data_pwd
    ports:
      - "5488:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  loki:
    image: grafana/loki:3.4.3@sha256:5fe9fa99e9a747297cdf0239a5b25d192d8f668bd6505b09beef4dffcab5aac2
    container_name: loki
    command:
      [
        "--validation.discover-service-name=[]",
        "--validation.discover-log-levels=false",
        "-config.file=/etc/loki/loki.yaml",
      ]
    volumes:
      - ./loki:/etc/loki/
    ports:
      - "3100:3100"
  prometheus:
    image: prom/prometheus:v3.2.1@sha256:6927e0919a144aa7616fd0137d4816816d42f6b816de3af269ab065250859a62
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  alertmanager:
    image: prom/alertmanager:v0.28.1@sha256:27c475db5fb156cab31d5c18a4251ac7ed567746a2483ff264516437a39b15ba
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager/
    ports:
      - 9093:9093
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-12.2.0}
    #image: grafana/grafana-oss:main
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp:25
      - GF_SMTP_SKIP_VERIFY=true
      - GF_FEATURE_TOGGLES_ENABLE=alertingCentralAlertHistory,sqlExpressions,alertingMigrationUI,grafanaManagedRecordingRules
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/alerting:/etc/grafana/provisioning/alerting
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
volumes:
  postgres:
    driver: local
