services:
  smtp:
    image: ixdotai/smtp:v0.7.7@sha256:4f5f64a386ef8e024b60a45f9cac171f6229dd65eaad1d772337a1db64ba7f3d
    container_name: smtp
    ports:
      - 127.0.0.1:25:25
    env_file:
      - ./environments/smtp.env
  postgres:
    image: postgres:18@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: my_data_db
      POSTGRES_USER: my_data_user
      POSTGRES_PASSWORD: my_data_pwd
    ports:
      - "5488:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  loki:
    image: grafana/loki:3.7.1@sha256:73e905b51a7f917f7a1075e4be68759df30226e03dcb3cd2213b989cc0dc8eb4
    container_name: loki
    command:
      [
        "--validation.discover-service-name=[]",
        "--validation.discover-log-levels=false",
        "-config.file=/etc/loki/loki.yaml",
      ]
    volumes:
      - ./loki:/etc/loki/
    ports:
      - "3100:3100"
  prometheus:
    image: prom/prometheus:v3.12.0@sha256:69f5241418838263316593f7274a304b095c40bcf22e57272865da91bd60a8ac
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  alertmanager:
    image: prom/alertmanager:v0.33.0@sha256:af26fbe4dd1886ac0efd7bd55cd9027da262e105b137a376522b7c14c3626e4a
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager/
    ports:
      - 9093:9093
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-12.3.1}
    #image: grafana/grafana-oss:main
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp:25
      - GF_SMTP_SKIP_VERIFY=true
      - GF_FEATURE_TOGGLES_ENABLE=alertingCentralAlertHistory,sqlExpressions,alertingMigrationUI,alertingImportYAMLUI,grafanaManagedRecordingRules
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/alerting:/etc/grafana/provisioning/alerting
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
volumes:
  postgres:
    driver: local
